# [START runtime]
runtime: python
api_version: 1
threadsafe: true
env: flex
service: backend
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    python_version: 3

resources:
  cpu: 2
  memory_gb: 6
  disk_size_gb: 10
# [END runtime]
